
name: OpenSprinkler
description: Home Assistant add-on for OpenSprinkler using vampywiz17/opensprinkler image.
url: https://github.com/vampywiz17/hassio-opensprinkler
image: vampywiz17/opensprinkler
arch: [ amd64, armv7 ]
ingress: true
ingress_port: 8080
panel_icon: "mdi:sprinkler-variant"

version: 0.0.5
slug: opensprinkler
startup: services
boot: auto
ports:
  8080/tcp: 5557
ports_description:
  8080/tcp: Web interface
options: {}
schema: {}
