
name: OpenSprinkler
description: Home Assistant add-on for OpenSprinkler using vampywiz17/opensprinkler image.
url: https://github.com/vampywiz17/hassio-opensprinkler
image: vampywiz17/opensprinkler
arch: [ amd64, i386 ]

version: 2.2.1.0
slug: opensprinkler
startup: services
boot: auto
ports:
  80/tcp: 5557
map:
  - type: addon_config
    read_only: False
    path: /config
options: {}
schema: {}
