
name: OpenSprinkler
description: Home Assistant add-on for OpenSprinkler using vampywiz17/opensprinkler image.
url: https://github.com/vampywiz17/hassio-opensprinkler
image: vampywiz17/opensprinkler
arch: [ amd64, armv7 ]

version: 0.0.3
slug: opensprinkler
startup: services
boot: auto
ports:
  8080/tcp: 5557
ports_description:
  8080/tcp: Web interface
options: {}
schema: {}
