name: OpenSprinkler
description: Home Assistant add-on for OpenSprinkler OSPi.
url: https://github.com/vampywiz17/hassio-opensprinkler

image: ghcr.io/vampywiz17/opensprinkler-ospi
version: "0.1.0"

slug: opensprinkler

arch:
  - amd64
  - aarch64

legacy: true

ingress: true
ingress_port: 8080
panel_icon: "mdi:sprinkler-variant"

startup: services
boot: auto

ports:
  8080/tcp: 5557

ports_description:
  8080/tcp: Web interface

options: {}
schema: {}
